### ISSUE TITLE
Create attendance tracker component for project teams

### ISSUE THREAD

**Issue by ElaineShu0312** [Codify-Club-Berkeley/internal-management-system#26]
- Only the project lead will be able to edit and save team attendance.
- Inspiration from CSM scheduler:
<img width="562" alt="Screenshot 2023-10-18 at 10 02 37 PM" src="https://github.com/Codify-Club-Berkeley/internal-management-system/assets/105891117/d458f06c-10be-4639-9baa-f3dcea713412">

<img width="579" alt="Screenshot 2023-10-18 at 10 02 49 PM" src="https://github.com/Codify-Club-Berkeley/internal-management-system/assets/105891117/e4d282e0-210e-43af-b796-08839aed9500">

<img width="534" alt="Screenshot 2023-10-18 at 10 03 14 PM" src="https://github.com/Codify-Club-Berkeley/internal-management-system/assets/105891117/c33109a4-28bc-4623-9350-905a52a964a9">

**Comment by ElaineShu0312** [comment]
To replace dummy data:
- Fetch the a specific project's meeting dates from backend in the desired format (Month/Day/Year).
- Display these dates in a list, sorted from most recent to least recent. 
- Fetch the member names from your database, and pass in (currently populated with dummy data)

**Comment by ElaineShu0312** [comment]
To Do:
- 

- [ ] check if a user has the project lead role, to be able to access attendance tracker. 
- [ ] - implement a save button that sends attendance data (dates, members, and attendance status) For ease and potentially to build in points, we can potentially have:

- present = 1
- unexcused absence = -1
- excused absence = 0

**Comment by aidansunbury** [comment]
@ElaineShu0312 I'm just going to close this issue for now, and we can revisit it once we have the needed things implemented on the backend
