### ISSUE TITLE
Creating a search bar for adding members to a project team for the ProjectManager component

### ISSUE THREAD

**Issue by syh379** [Codify-Club-Berkeley/internal-management-system#54]
- create a search bar that is at the top of the add member dropdown in the project manager component so we can type in the name of a member and have it show up at the dropdown to be selected/added to the project team
<img width="523" alt="Screenshot 2023-11-11 at 20 46 28" src="https://github.com/Codify-Club-Berkeley/internal-management-system/assets/103139270/cbc46e4b-54d4-443f-bcab-7f9877844bef">

**Comment by aidansunbury** [comment]
Was closed in #59
